name: cinemadle
description: "A new Flutter project."
publish_to: 'none'

version: 0.2.4+0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.9.0
  tmdb_repository:
    path: packages/tmdb_repository
  flutter_typeahead: ^5.2.0
  intl: ^0.19.0
  universal_io: ^2.2.2
  cupertino_icons: ^1.0.6
  flutter_flip_card: ^0.0.6
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - release_notes.txt
    - tmdb_logo.png
  fonts:
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoColorEmoji-Regular.ttf
          weight: 400