name: 'Run Unit Tests'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: pubspec.yaml

      - name: Get Packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run Tests
        run: flutter test
